language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

install:
  - yarn install --frozen-lockfile
  - yarn global add cloudfront-invalidate
  - mkdir wkhtmltopdf
  - wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - tar xvfJ wkhtmltox-0.12.4_linux-generic-amd64.tar.xz -C wkhtmltopdf
  - export PATH=$PATH:$PWD/wkhtmltopdf/wkhtmltox/bin

script: gulp

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_DEFAULT_REGION
  bucket: "sergeimikhailov.com"
  skip_cleanup: true
  local_dir: dist
  cache_control: "max-age=21600"
  on:
    branch: master

after_deploy:
  - cloudfront-invalidate -d $CLOUDFRONT_DISTRIBUTION_ID "/*"
