language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

install:
  - yarn install
  - yarn global add cloudfront-invalidate

script: gulp

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_DEFAULT_REGION
  bucket: "sergeimikhailov.com"
  skip_cleanup: true
  local_dir: dist
  cache_control: "max-age=21600"
  on:
    branch: master

after_deploy:
  - cloudfront-invalidate -d $CLOUDFRONT_DISTRIBUTION_ID "/*"
